# 2.3 矩阵消元

---

1.  第一步通过矩阵$E_{21}$乘以方程$A\boldsymbol{x}=\boldsymbol{b}$得到$E_{21}A\boldsymbol{x}=E_{21}\boldsymbol{b}$。
2.  矩阵$E_{21}A$在第2行第1列有一个0，因为消元。
3.  $E_{21}$是单位矩阵减去第二行第一列的乘数$a_{21}/a_{11}$。
4.  矩阵矩阵乘法是n个矩阵向量乘法：$\boldsymbol{E}\boldsymbol{A}=[\boldsymbol{E}a_1\dots\boldsymbol{E}a_n]$。
5.  在对等式左边进行乘法的时候，我们肯定会需要等式右边的$E\boldsymbol{b}$。所以可以认为是E在乘以一个增广矩阵$[A\boldsymbol{b}]=[a_1\dots a_n\ \boldsymbol{b}]$。
6.  消元就是将$A\boldsymbol{x}=\boldsymbol{b}$乘以$E_{21},E_{31},\dots,E_{n1}$，然后一列一列进行下去。
7.  行交换我们写作$P_{ij}$，表示ij行交换，我们用单位矩阵I的ij行交换来表示$P_{ij}$。

---

自此，我们将开始我们学习矩阵乘法的第一个例子。自然，我们开始的矩阵是一个包含了很多零的矩阵。我们目标是看看矩阵在做什么。E作用于一个向量b或者矩阵A从而产生了一个新的向量Eb或者一个新的矩阵EA。

我们第一个例子是“矩阵消元”。它们执行消元步骤。比如将第$j^{th}$个方程减去乘以$l_{th}$后的第$i^{th}$个方程。我们需要大量这样的的简单矩阵$E_{ij}$，在主对角线下消去每个非零值。

后面的章节，我们不会看到这些矩阵。它们是可以组合成一个矩阵E的。最简洁的方法是将它们的逆矩阵$(E_{ij})^{-1}$结合成为一个矩阵$L=E^{-1}$。这里是接下来内容的目的

1.  了解矩阵乘法每一步是怎么样的。
2.  组合所有的$E_{ij}$步骤到一个E矩阵。
3.  了解$E_{ij}$是怎么被它的逆矩阵$E_{ij}^{-1}$反转的。
4.  组合所有的逆矩阵$E_{ij}^{-1}$至L。

本节找到所有的矩阵$E_{ij}$。2.4节介绍四种矩阵相乘的方法。2.5节反转了这些步骤。

## 矩阵乘以向量Ax=b

这个3×3例子有一个很简短的Ax=b的类型：

$$\begin{equation}
\begin{matrix}2x_1+4x_2-2x_3=2\\4x_1+9x_2-3x_3=8\\-2x_1-3x_2+7x_3=10\end{matrix}\qquad 同于 \qquad \begin{bmatrix}2&4&-2\\4&9&-3\\-2&-3&7\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}=\begin{bmatrix}2\\8\\10\end{bmatrix}
\end{equation}$$

9个数字组成了矩阵A，A乘以x用于生成这三个方程。

总结一下A乘以x。A矩阵乘以一个向量会给出一个向量。矩阵是一个方阵，方程数量等于未知数的数量，也等于向量x的维度。

Ax是一个A的列的组合。为了计算Ax的分量，我们使用行形式的矩阵乘法。Ax的分量是A的行的点乘生成的。Ax的第i个分量是$(row\ i) \cdot\boldsymbol{x}=a_{i1}x_1+a_{i2}x_2+\cdots+a_{in}x_n$。

也可以写为$\sum_{j=1}^{n}a_{ij}x_j$。

## 消元步骤的矩阵表示

Ax=b形式的时候，消元步骤是怎么样的呢？不光左侧需要进行消元变换，等式右侧也在随之变换着，它也会执行第二行减去第一行乘以2的操作。

我们想要通过矩阵来实现这个操作。我们可以乘以一个矩阵E得到$\boldsymbol{b_{new}}=E\boldsymbol{b}$，其中矩阵E实现了消元：

$$消元矩阵\qquad E=\begin{bmatrix}1&0&0\\-2&1&0\\0&0&1\end{bmatrix}$$

乘以矩阵E使得第二行减去了第一行乘2。1和3行保持不变：

$$\begin{bmatrix}1&0&0\\-2&1&0\\0&0&1\end{bmatrix}\begin{bmatrix}2\\8\\10\end{bmatrix}=\begin{bmatrix}2\\4\\10\end{bmatrix}\qquad \begin{bmatrix}1&0&0\\-2&1&0\\0&0&1\end{bmatrix}\begin{bmatrix}b_1\\b_2\\b_3\end{bmatrix}=\begin{bmatrix}b_1\\b_2-2b_1\\b_3\end{bmatrix}$$

第1、3行是单位矩阵I。它们不改变第1、3个数字。

这样描述消元矩阵是很简单的。只需要从一个单位矩阵I开始，改变其中的0到乘数-l。

单位矩阵对角线是1其余的是0。然后Ib=b可以得到所有的b。初等矩阵或消元矩阵$E_{ij}$在i，j的位置有额外的非零项-l。

等式左边的情况是如何呢？左右两侧都被$E_{31}$相乘。其目的是在矩阵(3,1)的位置上产生一个0。

应用各种消去矩阵来使得主元产生一个一个的0。最终形成一个三角U。

这个消去矩阵$E_{ij}$是一个很好的例子，但是后面可能不会再看到了。它展示了矩阵如何作用在行上的。通过几个消去步骤，我们将看到如何乘矩阵，顺序也很重要。乘积和逆对于这些矩阵尤为重要。后续的内容将持续解释。

## 矩阵乘法

两个矩阵如何相乘呢？让我们从矩阵E开始，我们知道EA是如何解释的，第二行减去了第一行的两倍，乘数就是l=2：

$$\begin{equation}
EA=\begin{bmatrix}1&0&0\\-2&1&0\\0&0&1\end{bmatrix}\begin{bmatrix}2&4&-2\\4&9&-3\\-2&-3&7\end{bmatrix}=\begin{bmatrix}2&4&-2\\0&1&1\\-2&-3&7\end{bmatrix}
\end{equation}$$

矩阵乘法要注意一些规则：

结合律成立：A(BC)=(AB)C
交换律错误：通常AB≠BA

矩阵乘法还有一个需求。假设B只有一列，那么矩阵乘矩阵就与矩阵乘向量一致了。重要的是，我们要能够一次将矩阵EB的一列相乘：

如果矩阵B有一系列的列$b_1,b_2,b_3$，然后EB的列就是$Eb_1,Eb_2,Eb_3$。

$$\begin{equation}
矩阵乘法：AB=A[b_1\ b_2\ b_3]=[Ab_1\ Ab_2\ Ab_3]
\end{equation}$$

下一部分会描述矩阵乘积AB的每一项。矩阵乘法的美妙之处在于，无论是按行按列还是整个矩阵来看，所有的方法都是正确的。

## 矩阵$P_{ij}$来交换行

交换矩阵的两行，我们使用的是$P_{ij}$。直接举例，为了交换2和3行，我们修改了一个单位矩阵：

$$置换矩阵\qquad P_{23}=\begin{bmatrix}1&0&0\\0&0&1\\0&1&0\end{bmatrix}$$

行交换矩阵： $P_{ij}$是一个将单位矩阵中i和j行逆转的矩阵。当它乘以一个矩阵时，将会交换它们的ij行。

## 增广矩阵

这本书的内容最终也不会被淘汰的。矩阵有各种各样的应用，在这些应用中，它们时相乘的。我们最好的起点就是一个方阵E乘以一个方阵A，我们已经学过了EA的结果，下一步就是矩形矩阵，它仍是我们原来的方程，但是包含了右边的b。

关键思想：消元对于A到b的行做了同样的运算操作。我们可以将b作为一个额外的列接着进行消元。矩阵A通过b列进行了扩展或增广：

$$增广矩阵\qquad [A\quad \boldsymbol{b}]=\begin{bmatrix}2&4&-2&2\\4&9&-3&8\\-2&-3&7&10\end{bmatrix}$$

消去是作用于矩阵的整个行。左侧和右侧都会乘以E，让方程2去减去方程1乘以2：

$$\begin{bmatrix}1&0&0\\-2&1&0\\0&0&1\end{bmatrix}\begin{bmatrix}2&4&-2&2\\4&9&-3&8\\-2&-3&7&10\end{bmatrix}=\begin{bmatrix}2&4&-2&2\\0&1&1&4\\-2&-3&7&10\end{bmatrix}$$

新的运算的第二行包含了0、1、1、4。新的第二个方程是$x_2+x_3=4$。矩阵乘法可以按行和按列作用：

**行**：每行的E作用在[A&emsp;b]上可以给出[EA&emsp;Eb]的行。

**列**：每列的E作用在[A&emsp;b]上可以给出[EA&emsp;Eb]的列。

请注意作用在这个词，很重要。矩阵就是做了某些事情。矩阵A作用于x产生了b。矩阵E作用于A产生了EA。整个消去操作包含了一系列的行操作，也叫做矩阵乘法。$A$变成$E_{21}A$，然后变成$E_{31}E21A$，最后变成E32E31E21A，这是一个三角矩阵。

右侧包含在增广矩阵中。最终的结果就是一个三角形方程组。
