# 2.5 逆矩阵

---

1.  如果方阵A有逆矩阵，那么$A^{-1}A=I$和$AA^{-1}=I$都成立。
2.  可逆性的算法检验方法是消去法：A需要有n个非零的主元。
3.  可逆性的代数检验方法是A的行列式：det A必须不为零。
4.  可逆性的方程检验方法为Ax=0：x=0必须只有一个解。
5.  如果AB都是可逆的，那么：$(AB)^{-1}=B^{-1}A^{-1}$。
6.  $AA^{-1}=I$是n个关于$A^{-1}$列的方程。高斯消元会将$[A\ I]$变为$[I\ A^{-1}]$。
7.  最后给出了14个A可逆的等价条件。

---

假设A是方阵，那么A的逆矩阵也是同样的大小。A做什么，$A^{-1}$就会抵消他。

如果A是可逆的，那么$A^{-1}$就存在，也被称作为A逆。且以下等式成立：

$$\begin{equation}
A^{-1}A=I \qquad AA^{-1}I
\end{equation}$$

但不是所有的矩阵都有逆矩阵。这是我们关于方阵的第一个问题，A是否可逆。但这不意味着我们马上算出$A^{-1}$。许多情况下，我们是不会去算它的。以下是注意事项：

注意1：当且仅当消元产生n个主元的时候，逆存在。

注意2：矩阵A不存在两个不同的逆。

注意3：如果A是可逆的，$A\boldsymbol{x}=\boldsymbol{b}$有且仅有的解为$\boldsymbol{x}=A^{-1}\boldsymbol{b}$。

注意4（重要）：如果非零向量$\boldsymbol{x}$使得$A\boldsymbol{x}=0$。那么A向量是没有逆矩阵的，因为没有矩阵可以将0变回为x。

注意5：一个2×2的矩阵可逆，有且仅有ad-bc不为0时可以实现：

$$\begin{equation}
\begin{bmatrix}a&b\\c&d\end{bmatrix}^{-1}=\frac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}
\end{equation}$$

其中，ad-bc被称为A的行列式。A矩阵可逆的话，他的行列式不为零。

注意6：一个对角元素不为零的矩阵有逆矩阵：

$$A=\left[ \begin{array}{ccc}
b_1& & \\
 & \ddots& \\
  & & b_n \end{array} \right] \qquad 
  A^{-1}=\left[ \begin{array}{ccc}
  1/d_1& & \\
   & \ddots & \\
    & & 1/d_n
  \end{array}\right]$$

## AB的逆

对于两个数来说，a=3，b=-3。两者都有逆1/3和-1/3。但两者的和为0，没有逆。二者的积为-9，就有了逆。矩阵与这类似，A+B很难有一个固定的结论。当且仅当AB都分别有逆的时候，AB有逆：

$$\begin{equation}
(AB)^{-1}=B^{-1}A^{-1}
\end{equation}$$

这说明了一个基本的数学规则：逆的顺序是相反的。三者的时候也是这样的：

$$\begin{equation}
(ABC)^{-1}=C^{-1}B^{-1}A^{-1}
\end{equation}$$

逆矩阵与原矩阵的乘积由于顺序相反会出现一些现象，比如，我们有矩阵EF，二者都可逆。E的作用是将第二行减去5乘第一行，F作用是将第三行减去4乘第二行。那么我们来看FE的乘积与其逆有何不同，FE的第三行第一列会有一个新的数值20出现，而其逆则是0。这就是因为FE在先进行F变换的时候，第三行发生过一次变化，而其逆顺序调换先进行的是E的逆变换，没影响第三行的情况。注意：这就是下一节，我们选择A=LU的时候，从U到A乘数刚好落在下三角L上。

## 通过高斯消元计算$A^{-1}$

下面我们使用高斯消元法来求$A^{-1}$，也就是求解$AA^{-1}=1$。*A*乘以$A^{-1}$的第一列（x1）可以得到*I*的第一列（e1）。也就得到了$Ax_1=e_1=(1,0,0)$。同样还有另外两列的方程：

$$\begin{equation}
AA^{-1}=A[x_1\ \ x_2\ \ x_3]=[e_1\ \ e_2\ \ e_3]=I
\end{equation}$$

高斯消元法得到$A^{-1}$需要解n个方程。我们会构造一个$[A\ \ I]$，我们实际操作一下：

$$\begin{align}
\begin{bmatrix}K&e_1&e_2&e_3\end{bmatrix}&=\begin{bmatrix}2&-1&0&1&0&0\\-1&2&-1&0&1&0\\0&-1&2&0&0&1\end{bmatrix}\notag\\
&\to \begin{bmatrix}2&-1&0&1&0&0\\0&\frac{3}{2}&-1&\frac{1}{2}&1&0\\0&-1&2&0&0&1\end{bmatrix}\qquad(\frac{1}{2}\ row1+row2)\notag\\
&\to \begin{bmatrix}2&-1&0&1&0&0\\0&\frac{3}{2}&-1&\frac{1}{2}&1&0\\0&0&\frac{4}{3}&\frac{1}{3}&\frac{2}{3}&1\end{bmatrix}\qquad(\frac{2}{3}\ row2+row3) \notag
\end{align}$$

现在针对$K$矩阵我们有了$K^{-1}$，它的前三列是一个上三角矩阵U，主元2，$\frac{3}{2}$，$\frac{4}{3}$在对角线上。接下来是进行回代：

$$\begin{align}
&\to \begin{bmatrix}2&-1&0&1&0&0\\0&\frac{3}{2}&0&\frac{3}{4}&\frac{3}{2}&\frac{3}{4}\\0&0&\frac{4}{3}&\frac{1}{3}&\frac{2}{3}&1\end{bmatrix}\qquad(\frac{4}{3}\ row3+row2) \notag\\
&\to \begin{bmatrix}2&0&0&\frac{3}{2}&1&\frac{1}{2}\\0&\frac{3}{2}&0&\frac{3}{4}&\frac{3}{2}&\frac{3}{4}\\0&0&\frac{4}{3}&\frac{1}{3}&\frac{2}{3}&1\end{bmatrix}\qquad(\frac{2}{3}\ row2+row1) \notag
\end{align}$$

最后一步是单位化：

$$\begin{bmatrix}1&0&0&\frac{3}{4}&\frac{1}{2}&\frac{1}{4}\\0&1&0&\frac{1}{2}&1&\frac{1}{2}\\0&0&1&\frac{1}{4}&\frac{1}{2}&\frac{3}{4}\end{bmatrix}=\begin{bmatrix}I&x_1&x_2&x_3\end{bmatrix}=\begin{bmatrix}I&K^{-1}\end{bmatrix}$$

消去时将A变为I的同时创建了逆矩阵。对于大矩阵，可能不想要得到其逆矩阵，但对于小矩阵来说，得到逆矩阵是值得的。我们有以下规律：

1.  $K$在对角线上对称，那么$K^{-1}$也是如此。
2.  当$K$是三角矩阵（只有三个非零对角）的时候。$K^{-1}$是一个非零的密集矩阵。这也是我们不常计算逆矩阵的原因。
3.  主元的乘积是4，这也是矩阵$K$的行列式。

这就是为什么逆矩阵需要行列式不为0，因为我们要进行除法。

## 奇异与可逆

我们回到中心问题。哪些矩阵有逆矩阵？本节的开头提出了主元检验：当$A$有完整的n个主元时，$A^{-1}$存在。可以使用高斯消元来证明：

1.  有n个主元，消元需要解的方程是$Ax_i=e_i$。$x_i$的诸多列组成了$A^{-1}$。然后$AA^{-1}=I$，$A^{-1}$是右侧逆矩阵。
2.  消元实际上是一系列E，P，D的矩阵乘法。

证明略。

当且仅当三角矩阵对角线没有元素为0时，该三角矩阵可逆。

## 认识可逆矩阵

有些矩阵可以很快的分辨出是可逆矩阵。

对角占优矩阵是可逆的。（当矩阵的对角线元素都大于该行其余部分的总和时）