# 2.7 转置和排列

---

1.  $Ax$、$AB$和$A^{-1}$的转置是$x^{T}A^{T}$、$B^{T}A^{T}$和$(A^{T})^{-1}$。
2.  点积（内积）有$x\cdot y=x^{T}y$，这是$(1\times n)(n\times 1)=(1\times 1)$。外积为$xy^{T}=列\times 行=(n\times 1)(1\times n)=(n\times n)$。
3.  $Ax\cdot y=x\cdot A^{T}y$因为$(Ax)^{T}y=x^{T}A^{T}y=x^{T}(A^{T}y)$。
4.  对称矩阵$S^{T}=S$（乘积依然是对称的）。
5.  正交矩阵$Q^{T}=Q^{-1}$。Q的列向量是正交的单位向量。
6.  排列矩阵P与I有相同的行。有n!个不同的顺序。
7.  Px给分量$x_1,x_2,\dots, x_n$以新顺序排序。且$P^{T}=P^{-1}$。

---

我们还需要一个矩阵，比逆矩阵简单，叫转置矩阵。$A$的转置为$A^{T}$，列行转换。

如果A是m×n的，转置就是n×m：

如果$A=\begin{bmatrix}1&2&3\\0&0&4\end{bmatrix}$那么$A^{T}=\begin{bmatrix}1&0\\2&0\\3&4\end{bmatrix}$

其中$A^T$的第i行，第j列是A的第j行，第i列：

$(A^T)_{ij}=A_{ji}$

下三角矩阵的转置是上三角矩阵。

转置符合以下规则：

**加：**$A+B的转置是A^T+B^T$

**乘：**$AB的转置(AB)^T=B^TA^T$

**逆：**$(A^{-1})^T=(A^T)^{-1}$

从维度的角度来记忆理解会比较简单，A比如是m×t，B是t×n，AB就是m×n，AB转置就是n×m。由此来看A的转置t×m，B的转置n×t两者相乘要得到n×m的话，需要是B转置×A转置。

也有$(ABC)^T=C^TB^TA^T$。由此有：$A=LDU就有A^T=U^TD^TL^T$。对于主元矩阵$D=D^T$。

对于逆矩阵：$A^{-1}A=I$转置后有$A^T(A^{-1})^{T}=I$。

A转置可逆的条件是A可逆。

## 内积的意义

内积是x和y向量各项的乘积之和。让我们用矩阵来表示吧。

T在内：点积或内积是$x^Ty\qquad (1\times n)(n\times 1)$

T在外：第一级积或外积是$xy^T\qquad (n\times 1)(1\times n)$

$x^Ty$是一个数字，而$xy^T$是一个矩阵。量子力学中会将其写成< x|y >（内积）和|x >< y|（外积）。

还有三个内积有意义的例子：

力学：做功=(力)(距离)=$x^Tf$

电学：热损失=(电压降)(电流)=$e^Ty$

经济学：收入=(数量)(价格)=$q^Tp$

另外有$(Ax)^{T}y=x^{T}A^{T}y=x^{T}(A^{T}y)$

## 对称矩阵

对于一个对称矩阵来说，A和A的转置是没有区别的。我们将对称矩阵用字母S表示：

对称矩阵有：$S^T=S$，这意味着$s_{ji}=s_{ij}$。

对称矩阵的逆矩阵也是对称的，有：$(S^{-1})^T=(S^T)^{-1}=S^{-1}$。

## 构造对称矩阵：$A^TA$、$AA^T$、$LDL^T$

一个矩阵A（矩形矩阵也可），$A^TA$会自动生成一个对称矩阵。

$$\begin{equation}
A^TA的转置是A^T(A^T)^T
\end{equation}$$

矩阵$AA^T$也是对称矩阵，但是它是和$A^TA$不同的。根据经验大多数以矩形矩阵开始的都是以$A^TA$或$AA^T$结束的。

当对称矩阵消去时，因式分解为LDU时，$U=L^T$，也就是$S=LDL^T$。

## 排列矩阵

排列矩阵每一列都只有一个单独的1。$P^T$也是排列矩阵，两个排列矩阵的积也是排列矩阵。排列矩阵的逆矩阵也是排列矩阵。

最简单的排列矩阵P=I没有交换。然后就是行交换Pij。将I的所有可能的行交换列出来，就得到了所有可能的排列矩阵：

一个排列矩阵P有着单位矩阵I的所有行排序

重点：$P^{-1}$总是和$P^T$相等。$PP^T=I$

## 包括行交换的PA=LU因式分解

我们希望你能记住A=LU。它开始于$A=(E^{-1}_{21}\cdots E^{-1}_{ij}\cdots)U$。每个消去步骤都是由一个$E_{ij}$，并且由$E^{-1}_{ij}$逆转。这些逆被压缩为L。其对角线是1，结果是A=LU。

但是不是每个矩阵都可以这样的因式分解，有时需要进行行交换来产生主元。这些行交换被组合成了一个排列矩阵P。我们可以在消去前就进行行交换，也可以在消去后：（1）$PA=LU$（2）$A=L_1P_1U_1$。

$PA=LU$是常用的，可能不如$A=L_1P_1U_1$显得优雅。不必要在另一种形式上花费太多功夫，最重要的情况是P=I的情况，也就是没有行交换。